from __future__ import annotations

from mission_orchestrator.domain.phase import PhaseConfig, PhaseName

READ_TOOLS = ("Read", "Glob", "Grep")
ARTIFACT_TOOLS = (*READ_TOOLS, "Write")
STRUCTURE_TOOLS = (*READ_TOOLS, "WriteJson")
IMPL_TOOLS = (*ARTIFACT_TOOLS, "Edit", "Bash")
DESIGN_TOOLS = (*ARTIFACT_TOOLS, "CodeGraph", "GraphQuery", "GraphPropose")
IMPLEMENT_DESIGN_TOOLS = (*IMPL_TOOLS, "CodeGraph", "GraphQuery", "GraphPropose")
REVIEW_TOOLS = (*ARTIFACT_TOOLS, "WriteJson", "RunValidation")

GRAPH = "__graph_instructions__"

PHASES: dict[PhaseName, PhaseConfig] = {
    PhaseName.RESEARCH: PhaseConfig(
        PhaseName.RESEARCH,
        "researcher.md",
        "brainstorm-prompt.md",
        "brainstorm.md",
        DESIGN_TOOLS,
        75,
        1200,
        {
            "IDEA": "idea.md",
            "BRIEF_SEED": "brief-seed.md",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        harness_write_paths=("brainstorm.md",),
        harness_mutation_tools=("GraphPropose",),
    ),
    PhaseName.STRUCTURE: PhaseConfig(
        PhaseName.STRUCTURE,
        "structurer.md",
        "structure-prompt.md",
        None,
        STRUCTURE_TOOLS,
        30,
        1200,
        {"BRAINSTORM": "brainstorm.md", "BRIEF": "brief.md", "CHANGESET": "changeset.json"},
        harness_write_paths=("tasks.json",),
    ),
    PhaseName.GRILL: PhaseConfig(
        PhaseName.GRILL,
        "griller.md",
        "grill-prompt.md",
        "brief.md",
        DESIGN_TOOLS,
        50,
        3600,
        {
            "BRAINSTORM": "brainstorm.md",
            "BRIEF_SEED": "brief-seed.md",
            "TASKS": "tasks.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        is_conversation=True,
        harness_write_paths=("brief.md",),
        harness_mutation_tools=("GraphPropose",),
    ),
    PhaseName.SPEC: PhaseConfig(
        PhaseName.SPEC,
        "specifier.md",
        "spec-prompt.md",
        "spec.md",
        ARTIFACT_TOOLS,
        30,
        1200,
        {
            "CONTEXT_COLD": "context-cold.md",
            "CONTEXT_HOT": "context-hot.md",
            "BRAINSTORM": "brainstorm.md",
            "TASKS": "tasks.json",
            "BRIEF": "brief.md",
            "TASK_CONTRACT": "task-contract.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        harness_write_paths=("spec.md",),
    ),
    PhaseName.PLAN: PhaseConfig(
        PhaseName.PLAN,
        "planner.md",
        "plan-prompt.md",
        "plan.md",
        ARTIFACT_TOOLS,
        30,
        1200,
        {
            "CONTEXT_COLD": "context-cold.md",
            "CONTEXT_HOT": "context-hot.md",
            "BRAINSTORM": "brainstorm.md",
            "TASKS": "tasks.json",
            "BRIEF": "brief.md",
            "SPEC": "spec.md",
            "TASK_CONTRACT": "task-contract.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        harness_write_paths=("plan.md", "decisions.md"),
    ),
    PhaseName.IMPLEMENT: PhaseConfig(
        PhaseName.IMPLEMENT,
        "implementer.md",
        "implement-prompt.md",
        "status.md",
        IMPLEMENT_DESIGN_TOOLS,
        75,
        1200,
        {
            "CONTEXT_COLD": "context-cold.md",
            "CONTEXT_HOT": "context-hot.md",
            "SPEC": "spec.md",
            "PLAN": "plan.md",
            "DECISIONS": "decisions.md",
            "TASK_CONTRACT": "task-contract.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        allow_project_writes=True,
        harness_write_paths=("status.md",),
        harness_mutation_tools=("GraphPropose",),
    ),
    PhaseName.IMPLEMENT_BURSTS: PhaseConfig(
        PhaseName.IMPLEMENT_BURSTS,
        "implementer.md",
        "implement-burst-prompt.md",
        "status.md",
        IMPLEMENT_DESIGN_TOOLS,
        20,
        300,
        {
            "CONTEXT_COLD": "context-cold.md",
            "CONTEXT_HOT": "context-hot.md",
            "SPEC": "spec.md",
            "DECISIONS": "decisions.md",
            "TASK_CONTRACT": "task-contract.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        allow_project_writes=True,
        harness_write_paths=("_burst_progress.md", "status.md"),
        harness_mutation_tools=("GraphPropose",),
    ),
    PhaseName.REVIEW: PhaseConfig(
        PhaseName.REVIEW,
        "reviewer.md",
        "review-prompt.md",
        "audit.md",
        REVIEW_TOOLS,
        50,
        1200,
        {
            "SPEC": "spec.md",
            "PLAN": "plan.md",
            "DECISIONS": "decisions.md",
            "TASK_CONTRACT": "task-contract.json",
            "GRAPH_INSTRUCTIONS": GRAPH,
        },
        harness_write_paths=("audit.md", "review-evidence.json"),
    ),
    PhaseName.REIMPLEMENT: PhaseConfig(
        PhaseName.REIMPLEMENT,
        "implementer.md",
        "reimplement-prompt.md",
        "status.md",
        IMPLEMENT_DESIGN_TOOLS,
        75,
        1200,
        {
            "SPEC": "spec.md",
            "AUDIT": "audit.md",
            "STATUS": "status.md",
            "CONTEXT_HOT": "context-hot.md",
            "TASK_CONTRACT": "task-contract.json",
        },
        allow_project_writes=True,
        harness_write_paths=("status.md",),
        harness_mutation_tools=("GraphPropose",),
    ),
    PhaseName.COMPACT: PhaseConfig(
        PhaseName.COMPACT,
        "",
        "compact-prompt.md",
        None,
        ("Read", "Write"),
        10,
        1200,
        {"CONTEXT_HOT": "context-hot.md"},
        harness_write_paths=("_compact_tmp.md",),
    ),
    PhaseName.CONSOLIDATE: PhaseConfig(
        PhaseName.CONSOLIDATE,
        "",
        "consolidate-prompt.md",
        None,
        ("Read", "Write"),
        10,
        1200,
        {"TASKS": "tasks.json"},
        harness_write_paths=("tasks.json",),
    ),
    PhaseName.REPORT: PhaseConfig(
        PhaseName.REPORT,
        "",
        "report-full-prompt.md",
        None,
        ("Read", "Write", "Glob"),
        10,
        1200,
        {},
        harness_write_paths=("mission-report.md",),
    ),
    PhaseName.REPORT_PLAN: PhaseConfig(
        PhaseName.REPORT_PLAN,
        "",
        "report-plan-only-prompt.md",
        None,
        ("Read", "Write", "Glob"),
        10,
        1200,
        {},
        harness_write_paths=("mission-report.md",),
    ),
}


def get_phase_config(name: PhaseName) -> PhaseConfig:
    return PHASES[name]
