from __future__ import annotations

from pathlib import Path
from typing import Protocol


class ArtifactStore(Protocol):
    def exists(self, name: str) -> bool: ...
    def read_text(self, name: str, *, default: str | None = None) -> str: ...
    def write_text(self, name: str, content: str) -> None: ...
    def append_text(self, name: str, content: str) -> None: ...
    def delete(self, name: str) -> None: ...
    def path_for(self, name: str) -> Path: ...

