from __future__ import annotations

from pathlib import Path
from typing import Protocol


class GitService(Protocol):
    def detect_base_branch(self) -> str: ...
    def ensure_develop(self) -> str: ...
    def setup_branch(self, branch: str) -> str: ...
    def current_commit(self) -> str: ...
    def changed_files(self) -> list[str]: ...
    def changed_files_since(self, commit: str) -> list[str]: ...
    def stage_files(self, files: list[Path]) -> None: ...
    def final_commit(self, task_description: str, summary: str) -> None: ...
    def target_validation_available(self, project_dir: Path) -> bool: ...
    def run_target_validation(self, project_dir: Path) -> bool: ...
    def merge_to_develop(self, branch: str) -> bool: ...
