from __future__ import annotations

from typing import Protocol

from mission_orchestrator.domain.mission import GateMode, MissionSnapshot, WaitingApproval


class MissionStateStore(Protocol):
    def update_phase(self, snapshot: MissionSnapshot) -> None: ...
    def set_gate_mode(self, mode: GateMode) -> None: ...
    def get_gate_mode(self) -> GateMode: ...
    def set_waiting_approval(self, info: WaitingApproval | None) -> None: ...
    def mark_waiting_notified(self, notified: bool) -> None: ...
    def load_snapshot(self) -> MissionSnapshot | None: ...

